<?php

namespace FacturasBundle\Repository;

/**
 * EstimacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimacionRepository extends \Doctrine\ORM\EntityRepository
{
  public function valoresEstimacion()
  {
    return $this->getEntityManager()->getRepository('FacturasBundle:Estimacion')
                              ->createQueryBuilder('e')
                              ->setMaxResults(1)
                              ->getQuery()
                              ->getOneOrNullResult();
  }

  public function guardarEstimacion($estimacion)
  {
    $em = $this->getEntityManager();

    $em->createQueryBuilder()
                       ->delete('FacturasBundle:Estimacion')
                       ->getQuery()
                       ->getResult();

    $em->persist($estimacion);
    $em->flush();

  }
}
