<?php

namespace FacturasBundle\Repository;

/**
 * FacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaRepository extends \Doctrine\ORM\EntityRepository
{
  public function UltimaFactura()
  {
    return $this->getEntityManager()->getRepository("FacturasBundle:Factura")
                        ->createQueryBuilder('f')
                        ->orderBy('f.fecha','DESC')
                        ->setMaxResults(1)
                        ->getQuery()
                        ->getOneOrNullResult();

  }
}
