sessions:
    resource: "@SessionsBundle/Controller/"
    type:     annotation
    prefix:   /

facturas:
    resource: "@FacturasBundle/Resources/config/routing.yml"
    prefix:   /facturas

lecturas:
    resource: "@LecturasBundle/Resources/config/routing.yml"
    prefix:   /

estimacion_agregar:
  path: /estimacion
  defaults: { _controller: FacturasBundle:Facturas:estimacion }

app:
    resource: '@AppBundle/Controller/'
    type: annotation
