sessions:
    resource: "@SessionsBundle/Controller/"
    type:     annotation
    prefix:   /

facturas:
    resource: "@FacturasBundle/Resources/config/routing.yml"
    prefix:   /facturas

lecturas:
    resource: "@LecturasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
