services:
  LecturasBundle\Lavacharts\Lavacharts:
    arguments: [ '@doctrine.orm.default_entity_manager' ]
#    lecturas.example:
#        class: LecturasBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
