<?php

namespace LecturasBundle\Repository;

/**
 * LecturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturaRepository extends \Doctrine\ORM\EntityRepository
{
  public function UltimaLectura()
  {
    return $this->getEntityManager()
    			->getRepository("LecturasBundle:Lectura")
                ->createQueryBuilder('l')
                ->orderBy('l.fecha','DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();

  }

  public function lecturasPostFactura()
  {
  	
  	$ultimaFactura = $this->UltimaLectura();

  	return $this->getEntityManager()
  				->getRepository("LecturasBundle:Lectura")
                ->createQueryBuilder('l')
                ->where("l.fecha > '2017-10-02'")
                //->setParameter('fecha',$ultimaFactura->getFecha())
                ->orderBy('l.fecha','DESC')
                ->getQuery()
                ->getResult();

  }
}
