<?php

namespace LecturasBundle\Repository;
use LecturasBundle\Entity\Lectura;

/**
 * LecturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturaRepository extends \Doctrine\ORM\EntityRepository
{
  public function UltimaLectura()
  {
    return $this->getEntityManager()
    			->getRepository("LecturasBundle:Lectura")
                ->createQueryBuilder('l')
                ->orderBy('l.fecha','DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();

  }

  public function lecturasPostFactura()
  {


  	if(!$ultimaFactura = $this->getEntityManager()->getRepository("FacturasBundle:Factura")->UltimaFactura())
      $ultimaFactura = new Lectura;
    
  	return $this->getEntityManager()
  				->getRepository("LecturasBundle:Lectura")
                ->createQueryBuilder('l')
                //->where("l.fecha > :fecha")
                //->setParameter('fecha',$ultimaFactura->getFecha())
                ->where("l.fecha > '".$ultimaFactura->getFecha()->format('Y-m-d')."'")
                ->orderBy('l.fecha','DESC')
                ->getQuery()
                ->getResult();

  }


}
