<?php

namespace LecturasBundle\Repository;

/**
 * LecturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturaRepository extends \Doctrine\ORM\EntityRepository
{
}
